#=============================================================================
# Internet Telephony Software - (c) Copyright 2006, Internet Telephony Group
# Center for Development of Telematics (C-DOT), Bangalore, India.
# Filename     : makefile.path
# Description  : This file contains path which are exposed to user of this module
#			 and external dependent module path
# Author       : Vijaya Kumar
# Created On   : Wed Apr 19 14:35:58 IST 2006
# Last Modified:
#============================================================================

#-----------------------------------------------------------------------------
# BASE is set from makefile.inc which is included in all the makefile
#-----------------------------------------------------------------------------

#--------------------------------------------------------------
# External Module Dependent Path
#--------------------------------------------------------------
ifdef PIC
ECOS_DIR= /export/home1/seema/users/build-192.168.50.176/install
endif
ifdef GII
ECOS_DIR=/home/guest/users/vijayk/build-192.168.51.249/install
endif


#--------------------------------------------------------------
# Base Directory Path
#--------------------------------------------------------------
CDSU_UTIL_BASE_DIR= $(BASE_DIR)

#--------------------------------------------------------------
# Exposed to external world
#--------------------------------------------------------------
CDSU_UTIL_INCLUDE = $(CDSU_UTIL_BASE_DIR)/include
CDSU_UTIL_LIB_PATH = $(CDSU_UTIL_BASE_DIR)/src
CDSU_UTIL_LIB_NAME = cdsuutil

#============================================================================
# <End of makefile.path>
#============================================================================
