#=============================================================================
# BUK Assignment - (c) Copyright 2013 by Application Software Group
# Center for Development of Telematics (C-DOT), Bangalore, India.
#
# Filename	    : Makefile
# Description	: Makefile for basic utility kit assignment modules subdir
# Author	    :
# Created On	: 12.11.2013
# Last Modified :
#=============================================================================


# Sub Dir.
ADMINDIR=./admin
MENTORDIR=./mentor
TRAINEEDIR=./trainee
MYTRAINEEMENUDIR=./myTraineeMenu
# rohitm

all:

#admin:
	@cd $(ADMINDIR); $(MAKE)
#mentor:
	@cd $(MENTORDIR); $(MAKE)
#trainee:
	@cd $(TRAINEEDIR); $(MAKE)
#myTraineeMenu:
	@cd $(MYTRAINEEMENUDIR); $(MAKE)
# rohitm

clean: adminClean mentorClean traineeClean myTraineeMenuClean
# rohitm

adminClean:
	@cd $(ADMINDIR); $(MAKE) clean
mentorClean:
	@cd $(MENTORDIR); $(MAKE) clean
traineeClean:
	@cd $(TRAINEEDIR); $(MAKE) clean
myTraineeMenuClean:
	@cd $(MYTRAINEEMENUDIR); $(MAKE) clean
# rohitm

#=============================================================================
#<end of Makefile>
#=============================================================================
