#=============================================================================
# BUK Assignment - (c) Copyright 2013 by Application Software Group
# Center for Development of Telematics (C-DOT), Bangalore, India.
#
# Filename  	: Makefile
# Description	: Makefile for basic utility kit assignment src subdir
# Author	    : Trainee 2013
# Created On	: 12.11.2013
# Last Modified :
#=============================================================================

# Sub Dir.
BASICINFRADIR=./basicinfra
COMMONDIR=./common
MODULESDIR=./modules
UTIL=./util

all:
	@cd $(BASICINFRADIR); $(MAKE)
	@cd $(COMMONDIR); $(MAKE)
	@cd $(MODULESDIR); $(MAKE)

clean:
	@cd $(BASICINFRADIR); $(MAKE) clean
	@cd $(MODULESDIR); $(MAKE) clean
	@cd $(COMMONDIR); $(MAKE) clean

#=============================================================================
#<end of Makefile>
#=============================================================================
